name: tugboat
version: v0.2.0
summary: CL tool for interacting with DigitalOcean droplets.
description: |
  A command line tool for interacting with your 
  DigitalOcean droplets.


grade: devel
confinement: devmode

apps:
  tugboat:
    command: ruby $SNAP/bin/tugboat
    environment:
      GEM_HOME: $SNAP/gems
      GEM_PATH: $SNAP 

parts:
  tugboat:
    source: https://github.com/petems/tugboat.git
    plugin: ruby
    build: gem build tugboat.gemspec
    install: gem install tugboat-*.gem --env-shebang
    build-packages: [gcc, make, libc6-dev, ruby-dev]
    source-tag: v0.2.0

